import React from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Sparkles, CheckCircle, Clock, AlertTriangle, Zap, RefreshCw } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';

export default function AutoGeneratedTasksWidget({ agentId }) {
  const queryClient = useQueryClient();

  const { data: tasks = [], isLoading } = useQuery({
    queryKey: ['autoTasks', agentId],
    queryFn: () => base44.entities.Task.filter({
      assigned_to: agentId,
      auto_generated: true,
      status: 'pending'
    }, '-priority,-due_date'),
    enabled: !!agentId
  });

  const runBulkAnalysisMutation = useMutation({
    mutationFn: async () => {
      return await base44.functions.invoke('aiTaskAutomation', {
        trigger_type: 'bulk_analysis'
      });
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries(['autoTasks']);
      queryClient.invalidateQueries(['tasks']);
      toast.success(`Generated ${data.data.tasks_created} new tasks`);
    }
  });

  const completeTaskMutation = useMutation({
    mutationFn: (taskId) => base44.entities.Task.update(taskId, { status: 'completed' }),
    onSuccess: () => {
      queryClient.invalidateQueries(['autoTasks']);
      queryClient.invalidateQueries(['tasks']);
      toast.success('Task completed');
    }
  });

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'critical': return 'bg-red-100 text-red-700 border-red-200';
      case 'high': return 'bg-orange-100 text-orange-700 border-orange-200';
      case 'medium': return 'bg-amber-100 text-amber-700 border-amber-200';
      default: return 'bg-blue-100 text-blue-700 border-blue-200';
    }
  };

  const getCategoryIcon = (category) => {
    switch (category) {
      case 'client_retention': return AlertTriangle;
      case 'sales_opportunity': return Zap;
      case 'compliance': return Clock;
      default: return Sparkles;
    }
  };

  if (isLoading) {
    return (
      <Card className="border-0 shadow-sm dark:bg-slate-800">
        <CardContent className="pt-6">
          <div className="animate-pulse space-y-3">
            {[1,2,3].map(i => (
              <div key={i} className="h-16 bg-slate-200 dark:bg-slate-700 rounded" />
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-0 shadow-lg dark:bg-slate-800">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600" />
            AI-Generated Tasks
          </CardTitle>
          <Button
            size="sm"
            variant="outline"
            onClick={() => runBulkAnalysisMutation.mutate()}
            disabled={runBulkAnalysisMutation.isPending}
          >
            {runBulkAnalysisMutation.isPending ? (
              <>
                <RefreshCw className="w-4 h-4 mr-1 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <RefreshCw className="w-4 h-4 mr-1" />
                Generate Tasks
              </>
            )}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {tasks.length === 0 ? (
          <div className="text-center py-8">
            <Sparkles className="w-12 h-12 mx-auto text-slate-300 mb-3" />
            <p className="text-slate-500 text-sm">No AI-generated tasks yet</p>
            <Button
              size="sm"
              variant="outline"
              onClick={() => runBulkAnalysisMutation.mutate()}
              className="mt-3"
            >
              Run Analysis
            </Button>
          </div>
        ) : (
          <div className="space-y-3">
            {tasks.slice(0, 5).map(task => {
              const CategoryIcon = getCategoryIcon(task.category);
              const isOverdue = new Date(task.due_date) < new Date();
              
              return (
                <div
                  key={task.id}
                  className="p-3 rounded-lg border dark:border-slate-700 hover:border-purple-300 dark:hover:border-purple-600 transition-all"
                >
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-start gap-2 flex-1">
                      <CategoryIcon className="w-4 h-4 text-purple-600 mt-1 flex-shrink-0" />
                      <div className="flex-1 min-w-0">
                        <h4 className="font-medium text-sm text-slate-900 dark:text-white line-clamp-1">
                          {task.title}
                        </h4>
                        <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 line-clamp-2">
                          {task.description}
                        </p>
                      </div>
                    </div>
                    <Button
                      size="icon"
                      variant="ghost"
                      className="h-6 w-6 text-green-600"
                      onClick={() => completeTaskMutation.mutate(task.id)}
                    >
                      <CheckCircle className="w-4 h-4" />
                    </Button>
                  </div>
                  
                  <div className="flex items-center gap-2 mt-2">
                    <Badge className={getPriorityColor(task.priority)}>
                      {task.priority}
                    </Badge>
                    <Badge variant="outline" className="text-xs">
                      {task.category?.replace(/_/g, ' ')}
                    </Badge>
                    {task.due_date && (
                      <div className={`flex items-center gap-1 text-xs ${
                        isOverdue ? 'text-red-600' : 'text-slate-500'
                      }`}>
                        <Clock className="w-3 h-3" />
                        {format(new Date(task.due_date), 'MMM d')}
                      </div>
                    )}
                  </div>
                  
                  {task.ai_insights?.source && (
                    <div className="mt-2 text-xs text-purple-600 dark:text-purple-400">
                      Source: {task.ai_insights.source.replace(/_/g, ' ')}
                    </div>
                  )}
                </div>
              );
            })}
            
            {tasks.length > 5 && (
              <p className="text-center text-xs text-slate-500 pt-2">
                +{tasks.length - 5} more tasks
              </p>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}