import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Users, MessageSquare, Mail, Trophy, Rocket, Search, Filter, Plus, Phone, MapPin, Eye, Sparkles, Star } from 'lucide-react';
import { motion } from 'framer-motion';
import ClientFormModal from '../components/clients/ClientFormModal';
import AIOnboardingWorkflow from '../components/onboarding/AIOnboardingWorkflow';
import InteractionFormModal from '../components/clients/InteractionFormModal';
import PointsTracker from '../components/gamification/PointsTracker';
import RoleGuard from '../components/shared/RoleGuard';
import ClientChurnAnalysis from '../components/ai/ClientChurnAnalysis';
import AICoachingModule from '../components/coaching/AICoachingModule';
import AIClientAnalytics from '../components/ai/AIClientAnalytics';
import ProactiveClientMonitor from '../components/opportunities/ProactiveClientMonitor';
import ClientOnboardingFlow from '../components/onboarding/ClientOnboardingFlow';
import ClientOnboardingAutomation from '../components/onboarding/ClientOnboardingAutomation';
import AutoGeneratedTasksWidget from '../components/tasks/AutoGeneratedTasksWidget';
import AICRMIntelligence from '../components/crm/AICRMIntelligence';
import { toast } from 'sonner';
import SurveyResultsDashboard from '../components/surveys/SurveyResultsDashboard';

export default function ClientManagement() {
  const queryClient = useQueryClient();
  const [selectedClient, setSelectedClient] = useState(null);
  const [showClientForm, setShowClientForm] = useState(false);
  const [editingClient, setEditingClient] = useState(null);
  const [showInteractionForm, setShowInteractionForm] = useState(false);
  const [showEmailGenerator, setShowEmailGenerator] = useState(false);
  
  // Segmentation filters
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [planTypeFilter, setPlanTypeFilter] = useState('all');
  const [leadSourceFilter, setLeadSourceFilter] = useState('all');

  const { data: currentUser } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me()
  });

  const { data: agents = [] } = useQuery({
    queryKey: ['agents'],
    queryFn: () => base44.entities.Agent.list()
  });

  // Find agent linked to current user
  const currentAgent = agents.find(a => a.email === currentUser?.email) || agents[0];

  const { data: clients = [], isLoading: clientsLoading } = useQuery({
    queryKey: ['clients', currentAgent?.id],
    queryFn: () => currentAgent 
      ? base44.entities.Client.filter({ agent_id: currentAgent.id }, '-created_date')
      : [],
    enabled: !!currentAgent
  });

  const { data: interactions = [] } = useQuery({
    queryKey: ['interactions', currentAgent?.id],
    queryFn: () => currentAgent
      ? base44.entities.ClientInteraction.filter({ agent_id: currentAgent.id }, '-created_date')
      : [],
    enabled: !!currentAgent
  });

  const { data: agentPoints } = useQuery({
    queryKey: ['agentPoints', currentAgent?.id],
    queryFn: async () => {
      if (!currentAgent) return null;
      const points = await base44.entities.AgentPoints.filter({ agent_id: currentAgent.id });
      return points[0] || null;
    },
    enabled: !!currentAgent
  });

  const { data: allAgentPoints = [] } = useQuery({
    queryKey: ['allAgentPoints'],
    queryFn: () => base44.entities.AgentPoints.list()
  });

  const { data: achievements = [] } = useQuery({
    queryKey: ['achievements', currentAgent?.id],
    queryFn: () => currentAgent
      ? base44.entities.AgentAchievement.filter({ agent_id: currentAgent.id }, '-earned_date')
      : [],
    enabled: !!currentAgent
  });

  const { data: commissions = [] } = useQuery({
    queryKey: ['commissions'],
    queryFn: () => base44.entities.Commission.list()
  });

  const { data: licenses = [] } = useQuery({
    queryKey: ['licenses'],
    queryFn: () => base44.entities.License.list()
  });

  const { data: onboardingTasks = [] } = useQuery({
    queryKey: ['clientOnboardingTasks', currentAgent?.id],
    queryFn: () => currentAgent
      ? base44.entities.ClientOnboardingTask.filter({ agent_id: currentAgent.id }, '-created_date')
      : [],
    enabled: !!currentAgent
  });

  // Mutations
  const createClientMutation = useMutation({
    mutationFn: (data) => base44.entities.Client.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries(['clients']);
      setShowClientForm(false);
      toast.success('Client added');
      // Award points
      awardPoints(10, 'Client added');
    }
  });

  const updateClientMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Client.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries(['clients']);
      setShowClientForm(false);
      setEditingClient(null);
      toast.success('Client updated');
    }
  });

  const deleteClientMutation = useMutation({
    mutationFn: (id) => base44.entities.Client.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries(['clients']);
      setSelectedClient(null);
      toast.success('Client deleted');
    }
  });

  const createInteractionMutation = useMutation({
    mutationFn: async (data) => {
      // Create interaction
      await base44.entities.ClientInteraction.create(data);
      // Update client's last contact date
      await base44.entities.Client.update(data.client_id, {
        last_contact_date: new Date().toISOString().split('T')[0],
        ...(data.follow_up_required && data.follow_up_date ? { next_follow_up: data.follow_up_date } : {})
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries(['interactions']);
      queryClient.invalidateQueries(['clients']);
      setShowInteractionForm(false);
      toast.success('Interaction logged');
      // Award points
      awardPoints(5, 'Interaction logged');
    }
  });

  const saveEmailDraftMutation = useMutation({
    mutationFn: (data) => base44.entities.EmailDraft.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries(['emailDrafts']);
    }
  });

  // Points system
  const awardPoints = async (points, description) => {
    if (!currentAgent) return;
    
    try {
      if (agentPoints) {
        await base44.entities.AgentPoints.update(agentPoints.id, {
          points: (agentPoints.points || 0) + points,
          total_earned: (agentPoints.total_earned || 0) + points,
          monthly_points: (agentPoints.monthly_points || 0) + points,
          last_activity_date: new Date().toISOString().split('T')[0]
        });
      } else {
        await base44.entities.AgentPoints.create({
          agent_id: currentAgent.id,
          points,
          total_earned: points,
          monthly_points: points,
          level: 1,
          current_streak: 1,
          longest_streak: 1,
          last_activity_date: new Date().toISOString().split('T')[0]
        });
      }
      queryClient.invalidateQueries(['agentPoints']);
    } catch (err) {
      console.error('Failed to award points:', err);
    }
  };

  // Client segmentation and filtering
  const filteredClients = clients.filter(client => {
    const matchesSearch = !searchQuery || 
      `${client.first_name} ${client.last_name}`.toLowerCase().includes(searchQuery.toLowerCase()) ||
      client.email?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      client.phone?.includes(searchQuery);
    
    const matchesStatus = statusFilter === 'all' || client.status === statusFilter;
    const matchesPlanType = planTypeFilter === 'all' || client.plan_type === planTypeFilter;
    const matchesLeadSource = leadSourceFilter === 'all' || client.lead_source === leadSourceFilter;
    
    return matchesSearch && matchesStatus && matchesPlanType && matchesLeadSource;
  });

  const clientInteractions = selectedClient 
    ? interactions.filter(i => i.client_id === selectedClient.id)
    : [];

  const handleClientSubmit = (data) => {
    if (editingClient) {
      updateClientMutation.mutate({ id: editingClient.id, data });
    } else {
      createClientMutation.mutate(data);
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'active': return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400';
      case 'prospect': return 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400';
      case 'inactive': return 'bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-400';
      case 'churned': return 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  return (
    <RoleGuard pageName="ClientManagement">
      <div className="min-h-screen bg-slate-50 dark:bg-slate-900">
        <div className="w-full px-4 sm:px-6 lg:px-8 py-8">
          <div className="mb-8">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-teal-600 via-emerald-500 to-teal-600 dark:from-teal-400 dark:via-emerald-400 dark:to-teal-400 bg-clip-text text-transparent">
              Client Management
            </h1>
            <p className="text-slate-600 dark:text-slate-300 text-lg font-medium mt-2">
              Manage your clients, track interactions, and grow your book of business
            </p>
          </div>

          <Tabs defaultValue="clients" className="space-y-6">
            <TabsList className="clay-morphism p-1.5 rounded-2xl">
              <TabsTrigger value="clients" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Users className="w-5 h-5 mr-2" />
                Clients
              </TabsTrigger>
              <TabsTrigger value="ai-onboarding" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Sparkles className="w-5 h-5 mr-2" />
                AI Onboarding
              </TabsTrigger>
              <TabsTrigger value="onboarding" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Rocket className="w-5 h-5 mr-2" />
                Manual Onboarding
              </TabsTrigger>
              <TabsTrigger value="email" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Mail className="w-5 h-5 mr-2" />
                AI Emails
              </TabsTrigger>
              <TabsTrigger value="gamification" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Trophy className="w-5 h-5 mr-2" />
                Rewards
              </TabsTrigger>
              <TabsTrigger value="analytics" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Users className="w-5 h-5 mr-2" />
                AI Analytics
              </TabsTrigger>
              <TabsTrigger value="crm-intelligence" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Trophy className="w-5 h-5 mr-2" />
                CRM Intelligence
              </TabsTrigger>
              <TabsTrigger value="opportunities" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Sparkles className="w-5 h-5 mr-2" />
                Opportunities
              </TabsTrigger>
              <TabsTrigger value="surveys" className="rounded-xl data-[state=active]:clay-morphism data-[state=active]:bg-gradient-to-r data-[state=active]:from-teal-500 data-[state=active]:to-emerald-500 data-[state=active]:text-white data-[state=active]:shadow-lg">
                <Star className="w-5 h-5 mr-2" />
                Surveys
              </TabsTrigger>
              </TabsList>

            <TabsContent value="clients" className="space-y-6">
              {/* Segmentation Filters */}
              <Card className="clay-morphism border-0">
                <CardContent className="pt-6">
                  <div className="flex flex-col md:flex-row gap-4">
                    <div className="flex-1 relative">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-teal-500" />
                      <Input
                        placeholder="Search clients by name, email, or phone..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="pl-11 clay-subtle border-0 focus:ring-2 focus:ring-teal-500"
                      />
                    </div>
                    <Select value={statusFilter} onValueChange={setStatusFilter}>
                      <SelectTrigger className="w-40">
                        <SelectValue placeholder="Status" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Status</SelectItem>
                        <SelectItem value="active">Active</SelectItem>
                        <SelectItem value="prospect">Prospect</SelectItem>
                        <SelectItem value="inactive">Inactive</SelectItem>
                        <SelectItem value="churned">Churned</SelectItem>
                      </SelectContent>
                    </Select>
                    <Select value={planTypeFilter} onValueChange={setPlanTypeFilter}>
                      <SelectTrigger className="w-40">
                        <SelectValue placeholder="Plan Type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Plans</SelectItem>
                        <SelectItem value="medicare_advantage">Medicare Advantage</SelectItem>
                        <SelectItem value="supplement">Supplement</SelectItem>
                        <SelectItem value="pdp">PDP</SelectItem>
                        <SelectItem value="ancillary">Ancillary</SelectItem>
                      </SelectContent>
                    </Select>
                    <Select value={leadSourceFilter} onValueChange={setLeadSourceFilter}>
                      <SelectTrigger className="w-40">
                        <SelectValue placeholder="Lead Source" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Sources</SelectItem>
                        <SelectItem value="referral">Referral</SelectItem>
                        <SelectItem value="website">Website</SelectItem>
                        <SelectItem value="cold_call">Cold Call</SelectItem>
                        <SelectItem value="event">Event</SelectItem>
                        <SelectItem value="marketing">Marketing</SelectItem>
                      </SelectContent>
                    </Select>
                    <Button onClick={() => {
                      setEditingClient(null);
                      setShowClientForm(true);
                    }} className="clay-morphism bg-gradient-to-r from-teal-500 to-emerald-500 hover:from-teal-400 hover:to-emerald-400 text-white font-semibold shadow-xl shadow-teal-500/40 border-0">
                      <Plus className="w-5 h-5 mr-2" />
                      Add Client
                    </Button>
                  </div>
                  {(searchQuery || statusFilter !== 'all' || planTypeFilter !== 'all' || leadSourceFilter !== 'all') && (
                    <div className="flex items-center gap-2 mt-4">
                      <span className="text-sm text-slate-500">Showing {filteredClients.length} of {clients.length} clients</span>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => {
                          setSearchQuery('');
                          setStatusFilter('all');
                          setPlanTypeFilter('all');
                          setLeadSourceFilter('all');
                        }}
                      >
                        Clear Filters
                      </Button>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Client Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {clientsLoading ? (
                  [1,2,3,4,5,6].map(i => (
                    <Card key={i} className="border-0 shadow-sm dark:bg-slate-800 animate-pulse">
                      <CardContent className="pt-6">
                        <div className="h-20 bg-slate-200 dark:bg-slate-700 rounded" />
                      </CardContent>
                    </Card>
                  ))
                ) : filteredClients.length === 0 ? (
                  <Card className="col-span-full border-0 shadow-sm dark:bg-slate-800">
                    <CardContent className="pt-12 pb-12 text-center">
                      <Users className="w-12 h-12 mx-auto text-slate-300 mb-4" />
                      <p className="text-slate-500">No clients found</p>
                      <Button
                        onClick={() => {
                          setEditingClient(null);
                          setShowClientForm(true);
                        }}
                        className="mt-4 bg-teal-600 hover:bg-teal-700"
                      >
                        <Plus className="w-4 h-4 mr-2" />
                        Add Your First Client
                      </Button>
                    </CardContent>
                  </Card>
                ) : (
                  filteredClients.map(client => (
                    <motion.div whileHover={{ y: -4, scale: 1.01 }} key={client.id}>
                      <Card className="clay-morphism border-0 cursor-pointer group">
                        <CardHeader>
                          <div className="flex items-start justify-between">
                            <div>
                              <CardTitle className="text-lg font-bold text-slate-800 dark:text-white">{client.first_name} {client.last_name}</CardTitle>
                              <Badge className={`mt-2 clay-subtle ${getStatusColor(client.status)}`}>
                                {client.status}
                              </Badge>
                            </div>
                            <Link to={`${createPageUrl('ClientDetail')}?id=${client.id}`}>
                              <Button size="icon" className="clay-subtle hover:bg-teal-100 dark:hover:bg-teal-900/40 group-hover:scale-110 transition-transform">
                                <Eye className="w-5 h-5 text-teal-600 dark:text-teal-400" />
                              </Button>
                            </Link>
                          </div>
                        </CardHeader>
                      <CardContent className="space-y-2">
                        {client.email && (
                          <div className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-400">
                            <Mail className="w-4 h-4" />
                            <span className="truncate">{client.email}</span>
                          </div>
                        )}
                        {client.phone && (
                          <div className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-400">
                            <Phone className="w-4 h-4" />
                            <span>{client.phone}</span>
                          </div>
                        )}
                        {(client.city || client.state) && (
                          <div className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-400">
                            <MapPin className="w-4 h-4" />
                            <span>{client.city}, {client.state}</span>
                          </div>
                        )}
                        {client.plan_type && (
                          <div className="pt-2 border-t dark:border-slate-700">
                            <p className="text-xs text-slate-500">Plan Type</p>
                            <Badge variant="outline" className="mt-1 text-xs">
                              {client.plan_type.replace(/_/g, ' ')}
                            </Badge>
                          </div>
                        )}
                        </CardContent>
                        </Card>
                        </motion.div>
                        ))
                        )}
                        </div>
                        </TabsContent>

            <TabsContent value="ai-onboarding">
              <AIOnboardingWorkflow 
                agentId={currentAgent?.id}
                onComplete={(client) => {
                  queryClient.invalidateQueries(['clients']);
                  window.location.href = createPageUrl('ClientDetail') + `?id=${client.id}`;
                }}
              />
            </TabsContent>

            <TabsContent value="onboarding">
              <ClientOnboardingAutomation
                clients={clients}
                onboardingTasks={onboardingTasks}
                agent={currentAgent}
              />
            </TabsContent>

            <TabsContent value="email">
              <div className="space-y-6">
                <PointsTracker agentPoints={agentPoints} />
              </div>
            </TabsContent>

            <TabsContent value="gamification">
              <div className="space-y-6">
                <PointsTracker agentPoints={agentPoints} />
              </div>
            </TabsContent>

            <TabsContent value="crm-intelligence">
              <AICRMIntelligence 
                agentId={currentAgent?.id} 
                onCreateTask={async (taskData) => {
                  await base44.entities.Task.create(taskData);
                  queryClient.invalidateQueries(['tasks']);
                }}
              />
            </TabsContent>

            <TabsContent value="opportunities">
              <ProactiveClientMonitor agentId={currentAgent?.id} />
            </TabsContent>

            <TabsContent value="analytics">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2 space-y-6">
                  <AIClientAnalytics
                  clients={clients}
                  interactions={interactions}
                  agent={currentAgent}
                  onSendEmail={async (to, subject, body) => {
                    await base44.integrations.Core.SendEmail({ to, subject, body });
                    toast.success('Email sent');
                  }}
                  onCreateTask={async (taskData) => {
                    await base44.entities.Task.create(taskData);
                    queryClient.invalidateQueries(['tasks']);
                  }}
                  onSaveDraft={(data) => saveEmailDraftMutation.mutate(data)}
                />
                <ClientChurnAnalysis
                  clients={clients}
                  interactions={interactions}
                  agent={currentAgent}
                  onSendEmail={async (emailData) => {
                    await base44.integrations.Core.SendEmail({
                      to: emailData.client.email,
                      subject: emailData.subject,
                      body: emailData.body
                    });
                    toast.success('Email sent');
                  }}
                  onCreateTask={async (taskData) => {
                    await base44.entities.Task.create(taskData);
                    queryClient.invalidateQueries(['tasks']);
                  }}
                />
                </div>
                
                {/* AI Tasks Sidebar */}
                {currentAgent && (
                  <div>
                    <AutoGeneratedTasksWidget agentId={currentAgent.id} />
                  </div>
                )}
              </div>
            </TabsContent>
          </Tabs>
        </div>

        {/* Modals */}
        <ClientFormModal
          open={showClientForm}
          onClose={() => {
            setShowClientForm(false);
            setEditingClient(null);
          }}
          client={editingClient}
          agentId={currentAgent?.id}
          onSubmit={handleClientSubmit}
          isLoading={createClientMutation.isPending || updateClientMutation.isPending}
        />

        <InteractionFormModal
          open={showInteractionForm}
          onClose={() => setShowInteractionForm(false)}
          client={selectedClient}
          agentId={currentAgent?.id}
          onSubmit={(data) => createInteractionMutation.mutate(data)}
          isLoading={createInteractionMutation.isPending}
        />
      </div>
    </RoleGuard>
  );
}