import { useEffect } from 'react'
import { base44 } from '@/api/base44Client'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { createPageUrl } from '@/utils'
import { 
  Users, Shield, FileCheck, AlertTriangle, Plus, ArrowRight, 
  CheckSquare, Clock, BookOpen, Trophy, Brain
} from 'lucide-react';
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { motion } from 'framer-motion'
import { differenceInDays, format } from 'date-fns'
import StatsCard from '../components/dashboard/StatsCard';
import AlertsList from '../components/dashboard/AlertsList';
import ProactiveClientMonitor from '../components/opportunities/ProactiveClientMonitor';
import AgentStatusChart from '../components/dashboard/AgentStatusChart';
import AgentCard from '../components/agents/AgentCard';
import { checkLicenseExpirations, getLicenseExpirationSummary } from '../components/shared/licenseAlertChecker'
import { checkContractAlerts } from '../components/shared/contractAlertChecker'
import { useUserRole } from '../components/shared/RoleGuard'
import AutoGeneratedTasksWidget from '../components/tasks/AutoGeneratedTasksWidget';
import AICRMIntelligence from '../components/crm/AICRMIntelligence';
import AITaskPrioritizer from '../components/ai/AITaskPrioritizer';
import AIKnowledgeAssist from '../components/ai/AIKnowledgeAssist';
import ProactiveRiskMonitor from '../components/risk/ProactiveRiskMonitor';
import AgentPerformanceInsights from '../components/performance/AgentPerformanceInsights';
import ClientHealthOverview from '../components/dashboard/ClientHealthOverview';
import ContractComplianceMonitor from '../components/contracts/ContractComplianceMonitor';

export default function Dashboard() {
  const { user, isAdmin, isAgent, isSuperAdmin } = useUserRole();
  const queryClient = useQueryClient();

  const { data: agents = [], isLoading: agentsLoading } = useQuery({
    queryKey: ['agents'],
    queryFn: () => base44.entities.Agent.list('-created_date')
  });

  const currentAgent = agents.find(a => a.email === user?.email);

  const { data: licenses = [] } = useQuery({
    queryKey: ['licenses'],
    queryFn: () => base44.entities.License.list()
  });

  const { data: appointments = [] } = useQuery({
    queryKey: ['appointments'],
    queryFn: () => base44.entities.CarrierAppointment.list()
  });

  const { data: alerts = [] } = useQuery({
    queryKey: ['alerts'],
    queryFn: () => base44.entities.Alert.list('-created_date')
  });

  const { data: contracts = [] } = useQuery({
    queryKey: ['contracts'],
    queryFn: () => base44.entities.Contract.list()
  });

  const { data: tasks = [] } = useQuery({
    queryKey: ['tasks'],
    queryFn: () => base44.entities.Task.list('-created_date')
  });

  const { data: clients = [] } = useQuery({
    queryKey: ['clients'],
    queryFn: () => base44.entities.Client.list()
  });

  const resolveAlertMutation = useMutation({
    mutationFn: (alert) => base44.entities.Alert.update(alert.id, { 
      is_resolved: true, 
      resolved_date: new Date().toISOString() 
    }),
    onSuccess: () => queryClient.invalidateQueries(['alerts'])
  });

  const createAlertMutation = useMutation({
    mutationFn: (alertData) => base44.entities.Alert.create(alertData),
    onSuccess: () => queryClient.invalidateQueries(['alerts'])
  });

  const handleCreateTask = async (taskData) => {
    await base44.entities.Task.create(taskData);
    queryClient.invalidateQueries(['tasks']);
  };

  useEffect(() => {
    if (licenses.length > 0 && isAdmin) {
      checkLicenseExpirations(licenses, alerts, (alertData) => createAlertMutation.mutateAsync(alertData));
    }
  }, [licenses.length, isAdmin]);

  useEffect(() => {
    if (contracts.length > 0 && isAdmin) {
      checkContractAlerts(contracts, alerts, (alertData) => createAlertMutation.mutateAsync(alertData));
    }
  }, [contracts.length, isAdmin]);

  const licenseExpirationSummary = getLicenseExpirationSummary(licenses);
  const pendingTasks = tasks.filter(t => t.status === 'pending' || t.status === 'in_progress');
  const activeAlerts = alerts.filter(a => !a.is_resolved);

  const stats = {
    totalAgents: agents.length,
    readyToSell: agents.filter(a => a.onboarding_status === 'ready_to_sell').length,
    activeLicenses: licenses.filter(l => l.status === 'active').length,
    activeAlerts: activeAlerts.length,
    totalClients: clients.length
  };

  const getLicenseCount = (agentId) => licenses.filter(l => l.agent_id === agentId).length;
  const getAppointmentCount = (agentId) => appointments.filter(a => a.agent_id === agentId).length;
  const getAlertCount = (agentId) => alerts.filter(a => a.agent_id === agentId && !a.is_resolved).length;

  const recentAgents = agents.slice(0, 5);

  const quickActions = [
    { name: 'View Clients', icon: Users, page: 'ClientManagement', color: 'teal' },
    { name: 'Knowledge Base', icon: BookOpen, page: 'KnowledgeBase', color: 'blue' },
    { name: 'Leaderboard', icon: Trophy, page: 'Leaderboard', color: 'amber' },
  ];

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-gradient-to-br from-slate-50 via-slate-50 to-slate-100 dark:from-slate-900 dark:via-slate-900 dark:to-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <motion.div 
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6"
        >
          <div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-teal-600 via-emerald-500 to-teal-600 dark:from-teal-400 dark:via-emerald-400 dark:to-teal-400 bg-clip-text text-transparent">
              Welcome back{user?.full_name ? `, ${user.full_name.split(' ')[0]}` : ''}
            </h1>
            <p className="text-slate-600 dark:text-slate-300 text-lg font-medium mt-1">
              {isAdmin ? 'Medicare Advantage Agent Management' : 'Your agent portal'}
            </p>
          </div>
          {isAdmin && (
            <Link to={createPageUrl('AddAgent')}>
              <motion.div whileHover={{ y: -2, scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                <Button className="clay-morphism bg-gradient-to-r from-teal-500 to-emerald-500 hover:from-teal-400 hover:to-emerald-400 text-white font-semibold shadow-xl shadow-teal-500/40 border-0">
                  <Plus className="w-5 h-5 mr-2" />
                  Add Agent
                </Button>
              </motion.div>
            </Link>
          )}
        </motion.div>

        <div className="grid grid-cols-3 gap-4 mb-6">
          {quickActions.map((action, idx) => (
            <motion.div 
              key={action.page} 
              initial={{ opacity: 0, y: 20 }} 
              animate={{ opacity: 1, y: 0 }} 
              transition={{ delay: idx * 0.1 }}
              whileHover={{ y: -4 }}
            >
              <Link to={createPageUrl(action.page)}>
                <Card className="clay-morphism border-0 cursor-pointer group">
                  <CardContent className="p-4 flex items-center gap-3">
                    <div className="w-12 h-12 rounded-2xl clay-morphism bg-gradient-to-br from-teal-400 to-emerald-500 dark:from-teal-600 dark:to-emerald-700 flex items-center justify-center group-hover:scale-110 transition-all shadow-lg">
                      <action.icon className="w-6 h-6 text-white drop-shadow-lg" />
                    </div>
                    <span className="font-semibold text-slate-800 dark:text-white text-sm">{action.name}</span>
                    <ArrowRight className="w-5 h-5 text-teal-600 dark:text-teal-400 ml-auto group-hover:translate-x-2 transition-transform" />
                  </CardContent>
                </Card>
              </Link>
            </motion.div>
          ))}
        </div>

        {isAdmin && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
            {[
              { title: "Total Agents", value: stats.totalAgents, icon: Users, color: "teal" },
              { title: "Ready to Sell", value: stats.readyToSell, icon: FileCheck, color: "green", 
                trend: stats.totalAgents > 0 ? `${Math.round((stats.readyToSell / stats.totalAgents) * 100)}%` : undefined },
              { title: "Active Licenses", value: stats.activeLicenses, icon: Shield, color: "blue" },
              { title: "Active Alerts", value: stats.activeAlerts, icon: AlertTriangle, color: stats.activeAlerts > 0 ? "red" : "green" }
            ].map((stat, idx) => (
              <motion.div 
                key={stat.title} 
                initial={{ opacity: 0, y: 20 }} 
                animate={{ opacity: 1, y: 0 }} 
                transition={{ delay: idx * 0.1 }}
                whileHover={{ y: -4, scale: 1.02 }}
              >
                <div className="clay-morphism">
                  <StatsCard {...stat} />
                </div>
              </motion.div>
            ))}
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          <div className="lg:col-span-2 space-y-6">
              {/* Client Health Overview */}
              {currentAgent && (
                <ClientHealthOverview agentId={currentAgent.id} />
              )}

              {/* AI Automated Tasks */}
              {currentAgent && (
                <AgentAutomatedTasks agentId={currentAgent.id} compact />
              )}

              {/* Health Content Review */}
              {currentAgent && (
                <HealthContentReview agentId={currentAgent.id} />
              )}

              {/* Performance Insights */}
              {currentAgent && (
                <AgentPerformanceInsights agentId={currentAgent.id} compact />
              )}

              {/* Risk Monitoring */}
              {currentAgent && (
                <ProactiveRiskMonitor agentId={currentAgent.id} compact />
              )}

              {/* Proactive Opportunities */}
              {currentAgent && (
                <ProactiveClientMonitor agentId={currentAgent.id} compact />
              )}

              {/* AI CRM Intelligence */}
              {currentAgent && (
                <AICRMIntelligence agentId={currentAgent.id} onCreateTask={handleCreateTask} />
              )}

            {/* AI Efficiency Tools */}
            {currentAgent && (
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <AITaskPrioritizer agentId={currentAgent.id} />
                <AIKnowledgeAssist context="Agent Dashboard" />
              </div>
            )}

            {/* AI Task Widget for Agents */}
            {currentAgent && (
              <AutoGeneratedTasksWidget agentId={currentAgent.id} />
            )}
            {isAdmin && activeAlerts.length > 0 && (
              <AlertsList 
                alerts={alerts}
                compact
                onResolve={(alert) => resolveAlertMutation.mutate(alert)}
                onViewAgent={(agentId) => {
                  window.location.href = createPageUrl('AgentDetail') + `?id=${agentId}`;
                }}
              />
            )}

            {isAdmin && (
              <Card className="clay-morphism border-0">
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-base flex items-center gap-2 text-slate-800 dark:text-white">
                      <CheckSquare className="w-5 h-5 text-teal-600 dark:text-teal-400" />
                      Pending Tasks
                      {pendingTasks.length > 0 && <Badge variant="secondary" className="dark:bg-slate-700 dark:text-slate-300">{pendingTasks.length}</Badge>}
                    </CardTitle>
                    <Link to={createPageUrl('Tasks')}>
                      <Button variant="ghost" size="sm" className="text-teal-600">
                        View All <ArrowRight className="w-4 h-4 ml-1" />
                      </Button>
                    </Link>
                  </div>
                </CardHeader>
                <CardContent className="pt-0">
                  {pendingTasks.length === 0 ? (
                    <div className="text-center py-6">
                      <CheckSquare className="w-10 h-10 mx-auto text-slate-300 dark:text-slate-600 mb-2" />
                      <p className="text-sm text-slate-400 dark:text-slate-500">All caught up! No pending tasks.</p>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {pendingTasks.slice(0, 4).map(task => {
                        const isOverdue = task.due_date && differenceInDays(new Date(task.due_date), new Date()) < 0;
                        const agent = agents.find(a => a.id === task.agent_id);
                        return (
                          <div 
                            key={task.id}
                            className={`p-2.5 rounded-lg border ${isOverdue ? 'border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/30' : 'border-slate-100 bg-slate-50 dark:border-slate-700 dark:bg-slate-900/50'}`}
                          >
                            <div className="flex items-center justify-between gap-2">
                              <div className="flex-1 min-w-0">
                                <p className={`text-sm font-medium truncate ${isOverdue ? 'text-red-700 dark:text-red-400' : 'text-slate-700 dark:text-slate-200'}`}>
                                  {task.title}
                                </p>
                                <div className="flex items-center gap-2 mt-0.5 text-xs text-slate-500 dark:text-slate-400">
                                  {agent && <span>{agent.first_name} {agent.last_name}</span>}
                                  {task.due_date && (
                                    <span className={isOverdue ? 'text-red-500 dark:text-red-400' : ''}>
                                      <Clock className="w-3 h-3 inline mr-1" />
                                      {format(new Date(task.due_date), 'MMM d')}
                                    </span>
                                  )}
                                </div>
                              </div>
                              <Badge 
                                variant="outline" 
                                className={`text-xs shrink-0 ${
                                  task.priority === 'urgent' ? 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-400' :
                                  task.priority === 'high' ? 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-400' :
                                  'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-400'
                                }`}
                              >
                                {task.priority}
                              </Badge>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </CardContent>
              </Card>
            )}
            
            {isAdmin && <AgentStatusChart agents={agents} />}

            {isAgent && (
              <Card className="clay-morphism border-0 bg-gradient-to-r from-teal-50 to-emerald-50 dark:from-teal-900/30 dark:to-emerald-900/30">
                <CardContent className="p-5">
                  <h2 className="text-lg font-bold text-slate-800 dark:text-white mb-2">
                    👋 Welcome to AgentHub
                  </h2>
                  <p className="text-slate-600 dark:text-slate-300 mb-4 text-sm">
                    Your one-stop platform for managing clients, accessing resources, and growing your business.
                  </p>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-3 bg-white dark:bg-slate-800/80 rounded-lg border dark:border-slate-700">
                      <p className="text-2xl font-bold text-teal-600 dark:text-teal-400">{clients.length}</p>
                      <p className="text-xs text-slate-500 dark:text-slate-400">Your Clients</p>
                    </div>
                    <div className="p-3 bg-white dark:bg-slate-800/80 rounded-lg border dark:border-slate-700">
                      <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">{licenses.length}</p>
                      <p className="text-xs text-slate-500 dark:text-slate-400">Active Licenses</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
            </div>

            {isAdmin && (
            <motion.div 
            className="space-y-3"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            >
            {/* Contract Compliance Monitor */}
            <ContractComplianceMonitor agentId={null} />
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-teal-100 to-emerald-100 dark:from-teal-900/40 dark:to-emerald-900/40 flex items-center justify-center">
                    <Users className="w-3.5 h-3.5 text-teal-600 dark:text-teal-400" />
                  </div>
                  <h2 className="text-base font-semibold text-slate-800 dark:text-white">Recent Agents</h2>
                </div>
                <Link to={createPageUrl('Agents')}>
                  <motion.div 
                    whileHover={{ x: 5 }} 
                    className="text-sm text-teal-600 hover:text-teal-700 dark:text-teal-400 flex items-center gap-1 font-medium"
                  >
                    View All <ArrowRight className="w-4 h-4" />
                  </motion.div>
                </Link>
              </div>
            
              {agentsLoading ? (
                <div className="space-y-2">
                  {[1,2,3].map(i => (
                    <div key={i} className="h-20 bg-white dark:bg-slate-800 rounded-xl animate-pulse" />
                  ))}
                </div>
              ) : recentAgents.length === 0 ? (
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="bg-white dark:bg-slate-800 rounded-xl p-6 text-center shadow-sm border border-slate-200/50 dark:border-slate-700"
                >
                  <div className="w-12 h-12 rounded-full bg-gradient-to-br from-slate-100 to-slate-200 dark:from-slate-700 dark:to-slate-600 flex items-center justify-center mx-auto mb-3">
                    <Users className="w-6 h-6 text-slate-400 dark:text-slate-500" />
                  </div>
                  <p className="text-slate-600 dark:text-slate-300 font-semibold text-sm">No agents yet</p>
                  <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">Add your first agent to get started</p>
                  <Link to={createPageUrl('AddAgent')}>
                    <Button size="sm" className="mt-3 bg-gradient-to-r from-teal-600 to-teal-500 hover:from-teal-500 hover:to-teal-400 shadow-lg shadow-teal-500/30">
                      <Plus className="w-3 h-3 mr-1" />
                      Add Agent
                    </Button>
                  </Link>
                </motion.div>
              ) : (
                <div className="space-y-2">
                  {recentAgents.slice(0, 4).map((agent, index) => (
                    <motion.div
                      key={agent.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.4 + index * 0.1 }}
                    >
                      <AgentCard
                        agent={agent}
                        licenseCount={getLicenseCount(agent.id)}
                        appointmentCount={getAppointmentCount(agent.id)}
                        alertCount={getAlertCount(agent.id)}
                        appointments={appointments.filter(a => a.agent_id === agent.id)}
                        onClick={() => {
                          window.location.href = createPageUrl('AgentDetail') + `?id=${agent.id}`;
                        }}
                      />
                    </motion.div>
                  ))}
                </div>
              )}
            </motion.div>
          )}
        </div>
      </div>
    </div>
  );
}